import streamlit as st
import pandas as pd
from src.anomaly_engine import detect_anomalies, analyze_root_causes
from src.recommendation_engine import analyze_performance_gaps, analyze_anomaly_impact, generate_profit_strategy

st.set_page_config(layout="wide", page_title="AI Strategic Advisor")

st.title("💡 Strategic Recommendations")
st.markdown("Automated insights derived from performance data, anomaly clusters, and elasticity modeling.")

if 'df' not in st.session_state or st.session_state['df'] is None:
    st.warning("Please load data first.")
    st.stop()
    
df = st.session_state['df']

# --- RUN ANALYSIS ---
with st.spinner("Synthesizing strategies..."):
    # 1. Exec Summary Data
    exec_recs = analyze_performance_gaps(df)
    
    # 2. Anomaly Data (Using a balanced sensitivity for the 'General' check)
    raw_anomalies = detect_anomalies(df, contamination=0.05)
    analyzed_anomalies = analyze_root_causes(raw_anomalies, df)
    anomaly_recs = analyze_anomaly_impact(analyzed_anomalies)
    
    # 3. Forecast Strategy (Clean data first)
    clean_df = df.drop(raw_anomalies.index) if not raw_anomalies.empty else df
    strategy_recs = generate_profit_strategy(clean_df)

# --- DISPLAY LAYOUT ---

# SECTION 1: EXECUTIVE SUMMARY
st.header("1. Executive Summary")
col1, col2 = st.columns([1, 1])

# We split the recs for better visual balance
for i, rec in enumerate(exec_recs):
    target_col = col1 if i % 2 == 0 else col2
    with target_col:
        with st.container(border=True):
            if rec['type'] == 'Success':
                st.markdown(f"### ✅ Best Performer")
            elif rec['type'] == 'Warning':
                st.markdown(f"### ⚠️ Area of Concern")
            else:
                st.markdown(f"### 🎯 Action Item")
            st.markdown(rec['text'])

st.divider()

# SECTION 2: ANOMALY INTELLIGENCE
st.header("2. Anomaly Impact Analysis")
st.caption("Breakdown of financial leakage and primary statistical drivers.")

if anomaly_recs:
    # Highlight the "Critical" one big
    critical = [r for r in anomaly_recs if r['type'] == 'Critical']
    others = [r for r in anomaly_recs if r['type'] != 'Critical']
    
    if critical:
        st.error(critical[0]['text'], icon="🚨")
    
    # Show others as cards
    c_a, c_b = st.columns(2)
    for i, rec in enumerate(others):
        with c_a if i == 0 else c_b:
            st.info(rec['text'], icon="ℹ️")
else:
    st.success("No significant anomaly patterns detected requiring intervention.")

st.divider()

# SECTION 3: PROFIT OPTIMIZATION (Forecasting)
st.header("3. Profit Optimization Strategy (Next 30 Days)")
st.caption("Strategies generated by analyzing Price Elasticity of Demand (Cleaned of anomalies).")

if strategy_recs:
    # Display as a horizontal strategy list
    for rec in strategy_recs:
        color = "green" if "Profit" in rec['type'] else "blue" if "Volume" in rec['type'] else "gray"
        
        with st.container(border=True):
            cols = st.columns([0.5, 4])
            with cols[0]:
                st.markdown(f"## :{color}[$]")
            with cols[1]:
                st.markdown(f"**{rec['type']}**")
                st.markdown(rec['text'])
else:
    st.warning("Insufficient data variance to generate pricing strategies.")